# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          tongsonge
baseurl:        ""
url:            "http://www.tongsonge.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         tongsonge
  url:          http://tongsonge.com/
  email:        tongsonge@gmail.com
  github:       tongsonge
  twitter:

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/tongsonge/tongsonge.github.io
